---
- name: extract_and_install_lazydocker
  unarchive:
    src: "/tmp/lazydocker.tar.gz"
    dest: "/usr/local/bin/"
    remote_src: yes
  notify: cleanup_tarball

- name: cleanup_tarball
  file:
    path: "/tmp/lazydocker.tar.gz"
    state: absent
