---
- name: Disable systemd-resolved
  systemd:
    name: systemd-resolved.service
    enabled: false
    state: stopped

- name: Add dns=default to /etc/NetworkManager/NetworkManager.conf
  lineinfile:
    firstmatch: true
    path: "/etc/NetworkManager/NetworkManager.conf"
    insertafter: '[main]'
    line: "dns=default"

- name: Remove /etc/resolv.conf
  file:
    path: /etc/resolv.conf
    state: absent

- name: Restart Network-Manager systemd-resolved
  systemd:
    name: NetworkManager.service
    enabled: true
    state: restarted
