---
- name: apt packages tasks
  import_tasks: apt-packages.yml

- name: development tools and libraries tasks
  import_tasks: dev-packages.yml

- name: snap packages
  import_tasks: snap.yml

- name: authentication tasks
  import_tasks: authentication.yml

- name: security tasks
  import_tasks: security.yml

- name: optimize tasks
  import_tasks: optimize.yml

- name: powersave tasks
  import_tasks: powersave.yml

- name: keychron tasks
  import_tasks: keychron.yml

- name: autostart tasks
  import_tasks: autostart.yml
